name: Build and Publish Docker Image

on:
  push:
    branches:
      - release
    tags:
      - "v*.*.*" # Triggers on version tags (e.g., v1.0.0)
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: "0 0 5 * *" # Monthly on the 5st day at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/cryptodev .

      - name: Push the Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/cryptodev
          docker tag ghcr.io/${{ github.repository }}/cryptodev:latest ghcr.io/${{ github.repository }}/cryptodev:${{ github.ref_name }}
